In [2]:
import numpy as np
random_vector = np.random.uniform(1, 20, size=20)
print("Original array:")
print(random_vector)

reshaped_array = random_vector.reshape(4, 5)

max_indices = np.argmax(reshaped_array, axis=1)

reshaped_array[np.arange(4), max_indices] = 0

print("\nReshaped array:")
print(reshaped_array)


Original array:
[15.39769442 13.10496675 18.49860901 11.15699182  7.78986373 12.13487122
  2.25843629 15.70051464 15.41318803 12.37516949 13.42623028 19.1784791
 15.45425827 17.2276067  17.64831907  8.06539259  3.43394523 17.99074837
 15.25423275  5.95347635]

Reshaped array:
[[15.39769442 13.10496675  0.         11.15699182  7.78986373]
 [12.13487122  2.25843629  0.         15.41318803 12.37516949]
 [13.42623028  0.         15.45425827 17.2276067  17.64831907]
 [ 8.06539259  3.43394523  0.         15.25423275  5.95347635]]


In [1]:
class Employee:
    num_employees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.num_employees += 1

    @staticmethod
    def average_salary(employees):
        total_salary = sum(emp.salary for emp in employees)
        return total_salary / len(employees)

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, experience):
        super().__init__(name, family, salary, department)
        self.experience = experience

employee1 = Employee("John Doe", "Family A", 60000, "HR")
employee2 = Employee("Jane Smith", "Family B", 75000, "Finance")

fulltime_employee1 = FulltimeEmployee("Alice Johnson", "Family C", 80000, "IT", 3)
fulltime_employee2 = FulltimeEmployee("Bob Williams", "Family D", 90000, "Engineering", 5)

employees = [employee1, employee2, fulltime_employee1, fulltime_employee2]
avg_salary = Employee.average_salary(employees)

print("Total number of employees:", Employee.num_employees)
print("Average salary:", avg_salary)


Total number of employees: 4
Average salary: 76250.0
